# Generated by Django 5.2.8 on 2025-11-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='titulo',
            new_name='foto',
        ),
    ]
