# Generated by Django 5.2.8 on 2025-11-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_rename_titulo_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta'), ('BURACO NEGRO', 'Buraco Negro'), ('SATÉLITE', 'Satélite')], default='', max_length=60),
        ),
    ]
