# Generated by Django 5.2.8 on 2025-11-18 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='horario',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
