# Generated by Django 5.2.8 on 2025-11-18 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='horario',
            field=models.DateField(default=datetime.datetime(2025, 11, 18, 23, 20, 28, 96308, tzinfo=datetime.timezone.utc)),
        ),
    ]
