# Generated by Django 5.2.8 on 2025-11-18 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='horario',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 18, 23, 32, 21, 965854, tzinfo=datetime.timezone.utc)),
        ),
    ]
