# Generated by Django 5.2.8 on 2025-11-25 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='horario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
